### ISSUE TITLE
Node.js parse error in Logs

### ISSUE THREAD

**Issue by collinglass** [apex/go-apex#54]
What information do your need from me to better debug this error?

```
2017-05-20T12:18:29.139Z	6e248c53-3d56-11e7-b21c-3705fa92333b	SyntaxError: Unexpected token (
at Object.parse (native)
at LineStream.<anonymous> (/var/task/index.js:35:18)
at emitOne (events.js:77:13)
at LineStream.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:146:16)
at LineStream.Readable.push (_stream_readable.js:110:10)
at LineStream.Transform.push (_stream_transform.js:127:32)
at LineStream._pushBuffer (/var/task/byline.js:123:17)
at LineStream._transform (/var/task/byline.js:114:8)
at LineStream.Transform._read (_stream_transform.js:166:10)
```

**Comment by Heanthor** [comment]
You probably have something in your Go code printing to stdout instead of stderr.

**Comment by tj** [comment]
oh wow this is old hahah :D closing, but yep stdout is off limits for now
